# Generated by Django 3.2.25 on 2025-08-03 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
