# Generated by Django 3.2.25 on 2025-12-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogpost_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=50, unique=True, verbose_name='登录帐号')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('sex', models.CharField(max_length=1, verbose_name='性别')),
                ('gradeClass', models.CharField(max_length=15, verbose_name='年级班级')),
            ],
        ),
    ]
