# Generated by Django 3.2.25 on 2026-02-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='jiguan',
            field=models.CharField(max_length=30, null=True, verbose_name='籍贯'),
        ),
    ]
