# Generated by Django 3.2.25 on 2026-02-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_students_jiguan'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='icon',
            field=models.ImageField(null=True, upload_to='study/icon'),
        ),
    ]
